<?php

return [
    'icons' => [
        'default' => ['fas', 'flag'],
        'download' => ['fas', 'download'],
        'in-progress' => ['fas', 'cogs'],
        'waiting' => ['fas', 'pause'],
        'success' => ['fas', 'check'],
        'failed' => ['fas', 'exclamation-triangle'],
        'review' => ['fas', 'eye'],
        'star' => ['fas', 'star'],
        'search' => ['fas', 'search'],
        'view' => ['fas', 'search'],
        'filter' => ['fas', 'filter'],
        'error' => ['fas', 'bug'],
        'edit' => ['fas', 'edit'],
        'locked' => ['fas', 'lock'],
        'delete' => ['fas', 'trash'],
        'remove' => ['fas', 'times'],
        'add' => ['fas', 'plus'],
        'add-circle' => ['fas', 'plus-circle'],
        'refresh' => ['fas', 'sync'],
        'refresh-spin' => ['fas', 'sync', 'fa-spin'],
        'spinner-spin' => ['fas', 'spinner', 'fa-spin'],
        'cog-spin' => ['fas', 'cog', 'fa-spin'],
        'spinner-pulse' => ['fas', 'spinner', 'fa-pulse'],
        'telegram' => ['fab', 'telegram-plane'],
        'home' => ['fas', 'home'],
        'university' => ['fas', 'university'],
        'copyrigth' => ['fas', 'copyrigth'],
        'add' => ['fas', 'plus'],
        'file-csv' => ['fas', 'file-csv'],
        'validate' => ['fas', 'check'],
        'save' => ['fas', 'save'],
        'back' => ['fas', 'arrow-left'],
        'link' => ['fas', 'external-link-alt'],
        'openModal' => ['fas', 'external-link-alt'],
        'report' => ['fas', 'file-alt'],
        'tasks' => ['fas', 'tasks'],
        'user' => ['fas', 'user-circle'],
        'close' => ['fas', 'window-close'],
        'check' => ['fas', 'check-circle'],
        'chart-bar' => ['fas', 'chart-bar'],
    ]
];
